/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart.university.transport.system;

/**
 *
 * @author Golam Robbani
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
        setupDesign();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setupDesign() {

    // JFrame settings
    setTitle("Smart University Transport System - Admin Login");
    setSize(1000, 600);
    setLocationRelativeTo(null);
    setResizable(false);

    // ==============================
    // MAIN PANEL
    // ==============================

    javax.swing.JPanel mainPanel =
            new javax.swing.JPanel();

    mainPanel.setLayout(
            new java.awt.BorderLayout()
    );

    mainPanel.setBackground(
            new java.awt.Color(245, 247, 250)
    );


    // ==============================
    // LEFT PANEL
    // ==============================

    javax.swing.JPanel leftPanel =
            new javax.swing.JPanel();

    leftPanel.setBackground(
            new java.awt.Color(21, 101, 192)
    );

    leftPanel.setPreferredSize(
            new java.awt.Dimension(400, 600)
    );

    leftPanel.setLayout(
            new java.awt.GridBagLayout()
    );


    javax.swing.JLabel systemTitle =
            new javax.swing.JLabel();

    systemTitle.setText(
            "<html><center>"
            + "SMART UNIVERSITY<br>"
            + "TRANSPORT SYSTEM"
            + "</center></html>"
    );

    systemTitle.setFont(
            new java.awt.Font(
                    "Arial",
                    java.awt.Font.BOLD,
                    26
            )
    );

    systemTitle.setForeground(
            java.awt.Color.WHITE
    );

    systemTitle.setHorizontalAlignment(
            javax.swing.SwingConstants.CENTER
    );

    leftPanel.add(systemTitle);


    // ==============================
    // RIGHT PANEL
    // ==============================

    javax.swing.JPanel rightPanel =
            new javax.swing.JPanel();

    rightPanel.setBackground(
            new java.awt.Color(245, 247, 250)
    );

    rightPanel.setLayout(
            new java.awt.GridBagLayout()
    );


    // ==============================
    // LOGIN PANEL
    // ==============================

    javax.swing.JPanel loginPanel =
            new javax.swing.JPanel();

    loginPanel.setBackground(
            java.awt.Color.WHITE
    );

    loginPanel.setPreferredSize(
            new java.awt.Dimension(400, 400)
    );

    loginPanel.setLayout(
            new javax.swing.BoxLayout(
                    loginPanel,
                    javax.swing.BoxLayout.Y_AXIS
            )
    );

    loginPanel.setBorder(
            javax.swing.BorderFactory.createEmptyBorder(
                    35, 40, 35, 40
            )
    );


    // ==============================
    // LOGIN TITLE
    // ==============================

    javax.swing.JLabel loginTitle =
            new javax.swing.JLabel(
                    "Admin Login"
            );

    loginTitle.setFont(
            new java.awt.Font(
                    "Arial",
                    java.awt.Font.BOLD,
                    28
            )
    );

    loginTitle.setAlignmentX(
            javax.swing.JLabel.CENTER_ALIGNMENT
    );


    // ==============================
    // USERNAME
    // ==============================

    javax.swing.JLabel usernameLabel =
            new javax.swing.JLabel(
                    "Username"
            );

    usernameLabel.setFont(
            new java.awt.Font(
                    "Arial",
                    java.awt.Font.BOLD,
                    14
            )
    );

    usernameLabel.setAlignmentX(
            javax.swing.JLabel.LEFT_ALIGNMENT
    );


    javax.swing.JTextField usernameField =
            new javax.swing.JTextField();

    usernameField.setMaximumSize(
            new java.awt.Dimension(
                    300,
                    40
            )
    );


    // ==============================
    // PASSWORD
    // ==============================

    javax.swing.JLabel passwordLabel =
            new javax.swing.JLabel(
                    "Password"
            );

    passwordLabel.setFont(
            new java.awt.Font(
                    "Arial",
                    java.awt.Font.BOLD,
                    14
            )
    );

    passwordLabel.setAlignmentX(
            javax.swing.JLabel.LEFT_ALIGNMENT
    );


    javax.swing.JPasswordField passwordField =
            new javax.swing.JPasswordField();

    passwordField.setMaximumSize(
            new java.awt.Dimension(
                    300,
                    40
            )
    );


    // ==============================
    // LOGIN BUTTON
    // ==============================

    javax.swing.JButton loginButton =
            new javax.swing.JButton(
                    "LOGIN"
            );

    loginButton.setMaximumSize(
            new java.awt.Dimension(
                    300,
                    45
            )
    );

    loginButton.setAlignmentX(
            javax.swing.JLabel.LEFT_ALIGNMENT
    );

    loginButton.setBackground(
            new java.awt.Color(
                    21,
                    101,
                    192
            )
    );

    loginButton.setForeground(
            java.awt.Color.WHITE
    );

    loginButton.setFont(
            new java.awt.Font(
                    "Arial",
                    java.awt.Font.BOLD,
                    14
            )
    );

    loginButton.setFocusPainted(false);


    // ==============================
    // ADD COMPONENTS
    // ==============================

    loginPanel.add(loginTitle);

    loginPanel.add(
            javax.swing.Box.createVerticalStrut(30)
    );

    loginPanel.add(usernameLabel);

    loginPanel.add(
            javax.swing.Box.createVerticalStrut(8)
    );

    loginPanel.add(usernameField);

    loginPanel.add(
            javax.swing.Box.createVerticalStrut(20)
    );

    loginPanel.add(passwordLabel);

    loginPanel.add(
            javax.swing.Box.createVerticalStrut(8)
    );

    loginPanel.add(passwordField);

    loginPanel.add(
            javax.swing.Box.createVerticalStrut(30)
    );

    loginPanel.add(loginButton);


    // ==============================
    // ADD LOGIN PANEL
    // ==============================

    rightPanel.add(loginPanel);


    // ==============================
    // ADD LEFT + RIGHT
    // ==============================

    mainPanel.add(
            leftPanel,
            java.awt.BorderLayout.WEST
    );

    mainPanel.add(
            rightPanel,
            java.awt.BorderLayout.CENTER
    );


    // ==============================
    // PUT MAIN PANEL IN FRAME
    // ==============================

    getContentPane().removeAll();

    getContentPane().setLayout(
            new java.awt.BorderLayout()
    );

    getContentPane().add(
            mainPanel,
            java.awt.BorderLayout.CENTER
    );

    getContentPane().revalidate();

    getContentPane().repaint();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
